twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '@SonataForm/Form/datepicker.html.twig'
        #- '@SonataForm/Form/color.html.twig'
    cache: false

when@test:
    twig:
        strict_variables: true
